export { Caged } from "./client";
export { VERSION } from "./version";
export { TerminalSession } from "./terminal";
export { ExecStream } from "./stream";
export { MCPClient, MCPError } from "./mcp";
export type {
  MCPInitializeResult,
  MCPTool,
  MCPToolResult,
  MCPContentBlock,
  MCPResource,
  MCPResourceContent,
  MCPPrompt,
  MCPPromptResult,
} from "./mcp";
export { CLEAR_CREDENTIAL, EVENT_TYPES, mcpNeedsAllowRule } from "./types";
export type {
  Account,
  AccountSession,
  AgentSession,
  AgentSessionPage,
  Alert,
  AlertPage,
  AlertRule,
  AlertRuleUpdate,
  AlertSeverity,
  AlertState,
  APIKey,
  APIKeyScope,
  CagedConfig,
  CreatedAPIKey,
  EventPayload,
  ExecResult,
  FileEntry,
  GitDiff,
  GitFileStatus,
  IngestResponse,
  LogEntry,
  // Third-party MCP servers (client.mcp.*). MCPServerTool is deliberately not
  // MCPTool: that name already means "a tool on the agent's own MCP
  // connection" and is exported from ./mcp above.
  MCPAuthKind,
  MCPBinding,
  MCPBindParams,
  MCPBindResult,
  MCPCatalogueEntry,
  MCPGrantResult,
  MCPInputQuestion,
  MCPInputRequest,
  MCPOAuthAuthorization,
  MCPOAuthConsent,
  MCPOAuthProspect,
  MCPOAuthState,
  MCPOAuthStatus,
  MCPPolicyAdvice,
  MCPPolicyDecider,
  MCPPolicyStatus,
  MCPRefreshReport,
  MCPServer,
  MCPServerCreateParams,
  MCPServerDetail,
  MCPServerStatus,
  MCPServerTool,
  MCPToolDiff,
  MCPToolRevision,
  MCPToolState,
  Notification,
  NotificationConfig,
  NotificationConfigUpdate,
  NotificationPage,
  Pagination,
  Port,
  ProblemDetail,
  Refusal,
  ReplayEvent,
  ReplayPage,
  ReplaySummary,
  RuleConfig,
  Sandbox,
  SandboxConfigSummary,
  SandboxCreateParams,
  SandboxStatus,
  Session,
  SessionStatus,
  Snapshot,
  SnapshotCreateParams,
  SnapshotDownload,
  SocketTicket,
  Subscription,
  TrustScore,
  TrustScoreSummary,
  Usage,
  WebSocketFactory,
  WebSocketLike,
} from "./types";
export {
  CagedAPIError,
  CagedAuthError,
  CagedConnectionError,
  CagedError,
  CagedNotFoundError,
  CagedPlanLimitError,
  CagedRateLimitError,
  CagedServerError,
  CagedTimeoutError,
  CagedValidationError,
} from "./errors";
